const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: '/images/item-1.jpeg',
    desc: `A delicious stack of fluffy buttermilk pancakes drizzled with caramel syrup, topped with fresh strawberries and a dollop of whipped cream. A perfect breakfast treat!`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: '/images/item-2.jpeg',
    desc: `A juicy double-stacked burger loaded with melted cheese, lettuce, tomato, and crispy bacon, served with a side of golden fries. A classic diner favorite!`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: '/images/item-3.jpeg',
    desc: `A hearty breakfast plate featuring sunny-side-up eggs, crispy toast, and a cup of coffee—perfect for a morning boost!`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: '/images/item-4.jpeg',
    desc: `A hearty breakfast plate featuring sunny-side-up eggs, crispy toast, and a cup of coffee—perfect for a morning boost! `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: '/images/item-5.jpeg',
    desc: `A gourmet-style burger with a toasted sesame seed bun, fresh greens, melted cheese, and a thick beef patty, served with a side of vanilla bean for extra flavor. `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: '/images/item-6.jpeg',
    desc: `A rich and creamy chocolate milkshake topped with whipped cream, a fresh strawberry, and Oreo cookies, served in a stylish glass.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: '/images/item-7.jpeg',
    desc: ` A buttery, flaky biscuit sandwich stuffed with crispy bacon, a fried egg, and melted cheese—perfect for a satisfying breakfast on the go.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: '/images/item-8.jpeg',
    desc: `A simple yet mouthwatering cheeseburger with melted cheddar, paired with crispy golden fries and a side of ketchup. `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `A fun and wholesome moment of two people enjoying a creamy milkshake together while wearing masks, symbolizing a safe and sweet dining experience.`,
  },
];
export default menu;
